name: plot_neurips
channels:
  - conda-forge
  - javascript
dependencies:
  - IPython
  - matplotlib
  - pandas
  - pip>=21.0
  - pip:
    - ray
    - sklearn
    - submitit
  - python=3.7
  - pytorch=1.7
  - scipy
  - torchvision
